version: '3.3'
services:
  mysql:
    build: ./db
    image: pstyp94/trio
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment: 
     MYSQL_ROOT_PASSWORD: ${PASSWORD}
     MYSQL_DATABASE: flask-db 

  flask-app:
    build: ./flask-app
    image: pstyp94/trio2
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
     - mysql
    environment:
      DATABASE: ${DATABASE} 
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - flask-app
