version: '3.7'
services:
  mysql:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment: 
    - MYSQL_ROOT_PASSWORD=${PASSWORD}
    - MYSQL_DATABASE=flask-db 

  flask-app:
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
     - mysql
   
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - flask-app
